# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1 on 2026-08-09 18:39

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_atlas", "0001_initial"),
        ("django_atlas", "0002_observation"),
        ("django_atlas", "0003_sourceproductlink_uq_sourceproductlink_one_primary_per_sku"),
        ("django_atlas", "0004_alter_integrationevent_event_type_and_more"),
        ("django_atlas", "0005_sourcesettings_feed_scheduling_enabled"),
    ]

    dependencies = [
        ("django_pim", "0001_squashed_0060_productattribute_nulls_not_distinct"),
        ("django_regional", "0001_squashed_0006_country_default_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("auto_push_enabled", models.BooleanField(default=True)),
                ("scraper_dispatch_enabled", models.BooleanField(default=True)),
                ("delta_sync_enabled", models.BooleanField(default=True)),
                (
                    "feed_scheduling_enabled",
                    models.BooleanField(
                        default=True, help_text="Global killswitch for the dispatch_scheduled_feeds beat."
                    ),
                ),
                ("integration_event_retention_days", models.PositiveIntegerField(default=90)),
                ("change_log_retention_days", models.PositiveIntegerField(default=90)),
                ("import_log_retention_days", models.PositiveIntegerField(default=90)),
                (
                    "observation_retention_days",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-kind retention window in days, e.g. {'monitoring': 180, 'enrichment': 180}. Missing kind keys fall back to 180 (see tasks/observation_retention.py).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Settings",
                "verbose_name_plural": "Source Settings",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("procurement", "Procurement"),
                            ("monitoring", "Monitoring"),
                            ("enrichment", "Enrichment"),
                        ],
                        default="procurement",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("feed", "Feed"), ("manual", "Manual"), ("dropship", "Dropship")],
                        default="feed",
                        max_length=20,
                    ),
                ),
                (
                    "review_mode",
                    models.CharField(choices=[("manual", "Manual"), ("auto", "Auto")], default="manual", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_trusted",
                    models.BooleanField(
                        default=True,
                        help_text="Generic reliability flag. Downstream consumers (e.g. pricefighter) may filter to trusted-only sources.",
                    ),
                ),
                ("sku_prefix", models.CharField(default="", max_length=10)),
                ("default_feature_set_idx", models.CharField(blank=True, max_length=64, null=True)),
                ("target_warehouse_code", models.CharField(blank=True, max_length=64, null=True)),
                ("default_product_class", models.PositiveSmallIntegerField(default=1)),
                (
                    "realproduct_match_tolerance_pct",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Max acceptable per-field diff (%) when EAN-matching an existing RealProduct.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "realproduct_match_strict",
                    models.BooleanField(
                        default=False,
                        help_text="When True, missing physical field on either side fails tolerance (no skip).",
                    ),
                ),
                (
                    "disable_ean_auto_link",
                    models.BooleanField(
                        default=False,
                        help_text="When True, init push never tries EAN-based RealProduct lookup (per-source opt-out).",
                    ),
                ),
                (
                    "allow_physical_writes_from_non_primary",
                    models.BooleanField(
                        default=False,
                        help_text="When True, this source's delta sync may overwrite RealProduct physical fields (weight, ean, width, height, deep) even if its link is not primary. Default False — primary is the single source of truth. Opt-in only for vendor-tested measurement use cases (audited as physical_update_overwrite warning event).",
                    ),
                ),
                (
                    "primary_strategy",
                    models.CharField(
                        choices=[
                            ("lowest_cost_with_stock", "Lowest cost with stock"),
                            ("highest_stock", "Highest stock"),
                            ("manual_only", "Manual only"),
                        ],
                        default="lowest_cost_with_stock",
                        help_text="Picker strategy for auto-primary evaluation across this source's links.",
                        max_length=32,
                    ),
                ),
                (
                    "primary_switch_cooldown_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Minimum hours between consecutive auto-primary switches on the same RealProduct.",
                    ),
                ),
                (
                    "primary_switch_hysteresis_pct",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Minimum cost-improvement (%) required before auto-primary swaps the winner.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "eval_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("hourly", "Hourly"), ("manual", "Manual")],
                        default="daily",
                        help_text="How often the auto-primary cron evaluates this source's RealProducts.",
                        max_length=16,
                    ),
                ),
                (
                    "qty_subtract",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "qty_minimum",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ("company_name", models.CharField(blank=True, default="", max_length=128)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=32)),
                ("contact_person", models.CharField(blank=True, default="", max_length=128)),
                ("notes", models.TextField(blank=True, default="")),
                ("lead_time_days", models.IntegerField(blank=True, null=True)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_regional.country",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_regional.currency",
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="django_regional.currency"
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="django_regional.language"
                    ),
                ),
            ],
            options={
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("procurement", "Procurement"),
                            ("monitoring", "Monitoring"),
                            ("enrichment", "Enrichment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.JSONField()),
                ("ts", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="django_atlas.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.SlugField(max_length=64)),
                ("connector_kind", models.CharField(max_length=64)),
                ("feed_config", models.JSONField(blank=True, default=dict)),
                ("schedule_cron", models.CharField(blank=True, default="", max_length=64)),
                (
                    "sync_mode",
                    models.CharField(choices=[("full", "Full"), ("delta", "Delta")], default="full", max_length=10),
                ),
                ("feature_set_idx", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, default="", max_length=20)),
                ("last_run_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_regional.currency",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_regional.language",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feeds", to="django_atlas.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "mode",
                    models.CharField(choices=[("full", "Full"), ("delta", "Delta"), ("test", "Test")], max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("new_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("delisted_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("pushed_delisted_count", models.PositiveIntegerField(default=0)),
                ("mass_delisting_triggered", models.BooleanField(default=False)),
                ("physical_updated_count", models.PositiveIntegerField(default=0)),
                ("physical_skipped_non_primary_count", models.PositiveIntegerField(default=0)),
                ("physical_overwrite_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[("cli", "CLI"), ("api", "API"), ("scheduler", "Scheduler"), ("signal", "Signal")],
                        max_length=10,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_logs",
                        to="django_atlas.sourcefeed",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceMappingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("target_channel_idxs", models.JSONField(blank=True, default=list)),
                ("feature_set_idx", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "import_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_regional.language",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_profiles",
                        to="django_atlas.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceCategoryMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("source_field", models.CharField(max_length=128)),
                ("source_value", models.CharField(max_length=512)),
                ("target_category_idx", models.CharField(max_length=64)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="django_atlas.sourcemappingprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceAttributeMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("source_field", models.CharField(max_length=128)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("feature", "Feature"), ("real_product", "Real product"), ("skip", "Skip")],
                        max_length=20,
                    ),
                ),
                ("target_identifier", models.CharField(blank=True, default="", max_length=128)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "modifier",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("grams_to_kg", "Grams -> kg (/1000)"),
                            ("kg_to_grams", "Kg -> grams (x1000)"),
                            ("mm_to_cm", "mm -> cm (/10)"),
                            ("cm_to_mm", "cm -> mm (x10)"),
                            ("mm_to_m", "mm -> m (/1000)"),
                            ("currency_minor_to_major", "Currency minor -> major (/100)"),
                            ("currency_major_to_minor", "Currency major -> minor (x100)"),
                            ("string_trim", "String trim"),
                            ("string_lowercase", "String lowercase"),
                            ("string_uppercase", "String uppercase"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_mappings",
                        to="django_atlas.sourcemappingprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("external_id_history", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(db_index=True, max_length=512)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, help_text="Procurement: purchase cost.", max_digits=12, null=True
                    ),
                ),
                (
                    "observed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Monitoring: observed competitor price. clean() rejects this when source.kind != monitoring.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "signals",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Enrichment: arbitrary signal payload (e.g. Steam metadata).",
                        null=True,
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("stock", models.IntegerField(blank=True, null=True)),
                ("ean", models.CharField(blank=True, db_index=True, default="", max_length=14)),
                ("url", models.URLField(blank=True, default="", max_length=2048)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("data_hash", models.CharField(blank=True, db_index=True, default="", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("queued", "Queued"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pushed_pending_images", "Pushed (pending images)"),
                            ("pushed", "Pushed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                ("feature_set_idx_override", models.CharField(blank=True, max_length=64, null=True)),
                ("pushed_to_channel_idxs", models.JSONField(blank=True, default=list)),
                ("images_complete_channel_idxs", models.JSONField(blank=True, default=list)),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("data_changed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("physical_changed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="django_atlas.sourcefeed",
                    ),
                ),
                (
                    "pushed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "real_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_products",
                        to="django_pim.realproduct",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="django_atlas.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("feed_failed", "Feed failed"),
                            ("scraper_banned", "Scraper banned"),
                            ("scraper_dispatch_skipped", "Scraper dispatch skipped"),
                            ("image_failed", "Image failed"),
                            ("push_failed", "Push failed"),
                            ("push_succeeded", "Push succeeded"),
                            ("cost_updated", "Cost updated"),
                            ("mass_delisting", "Mass delisting"),
                            ("feed_no_run", "Feed no run"),
                            ("pim_feature_missing", "PIM feature missing"),
                            ("qms_not_installed_skipped", "QMS not installed (skipped)"),
                            ("qms_warehouse_not_configured", "QMS warehouse not configured"),
                            ("qms_write_failed", "QMS write failed"),
                            ("pushed_product_delisted", "Pushed product delisted"),
                            ("ean_collision_detected", "EAN collision detected"),
                            ("unknown_external_id_in_delta", "Unknown external_id in delta"),
                            ("physical_update_applied", "Physical update applied"),
                            ("force_repush_executed", "Force re-push executed"),
                            ("import_completed", "Import completed"),
                            ("source_deleted", "Source deleted"),
                            ("channel_removed_from_profile", "Channel removed from profile"),
                            ("attribute_value_missing", "Attribute value missing"),
                            ("pim_attribute_missing", "PIM attribute missing"),
                            ("pim_category_missing", "PIM category missing"),
                            ("pim_feature_set_missing", "PIM feature_set missing"),
                            ("pim_channel_missing", "PIM channel missing"),
                            ("image_download_started", "Image download started"),
                            ("image_download_completed", "Image download completed"),
                            ("multi_source_overlap", "Multi-source overlap"),
                            ("stock_updated", "Stock updated"),
                            ("qms_no_real_product", "QMS no real_product"),
                            ("cost_missing", "Cost missing"),
                            ("currency_missing", "Currency missing"),
                            ("scraper_results_validation_errors", "Scraper results validation errors"),
                            ("scraper_unknown_run_id", "Scraper unknown run_id"),
                            ("scraper_callback_signature_invalid", "Scraper callback signature invalid"),
                            ("source_credentials_viewed", "Source credentials viewed"),
                            ("source_credentials_updated", "Source credentials updated"),
                            ("language_fallback", "Language fallback"),
                            ("mapping_transform_failed", "Mapping transform failed"),
                            ("auto_linked_to_existing_realproduct", "Auto-linked to existing RealProduct"),
                            ("physical_tolerance_violation", "Physical tolerance violation"),
                            ("manual_unlink_from_realproduct", "Manual unlink from RealProduct"),
                            ("primary_source_switched", "Primary source switched"),
                            ("primary_source_emergency_switch", "Primary source emergency switch"),
                            ("primary_source_forced", "Primary source forced (manual override)"),
                            ("primary_switch_skipped_cooldown", "Primary switch skipped (cooldown)"),
                            ("primary_switch_skipped_hysteresis", "Primary switch skipped (hysteresis)"),
                            ("primary_switch_skipped_manual_override", "Primary switch skipped (manual override)"),
                            ("realproduct_manually_merged", "RealProduct manually merged"),
                            ("physical_update_skipped_non_primary", "Physical update skipped (non-primary)"),
                            ("physical_update_overwrite", "Physical update overwrite (opt-in non-primary)"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("warning", "Warning"), ("info", "Info")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="django_atlas.source",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_events",
                        to="django_atlas.sourcefeed",
                    ),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_events",
                        to="django_atlas.sourceproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceProductChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("real_product_sku", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("full_sync", "Full sync"),
                            ("delta_sync", "Delta sync"),
                            ("init_push", "Init push"),
                            ("force_repush", "Force re-push"),
                            ("operator_sp_edit", "Operator SP edit"),
                            ("auto_link", "Auto EAN link"),
                            ("auto_primary_switch", "Auto primary switch"),
                            ("manual_override", "Manual override"),
                            ("emergency_switch", "Emergency switch"),
                            ("operator_acknowledge", "Operator acknowledge"),
                            ("language_fallback", "Language fallback"),
                            ("mapping_transform", "Mapping transform"),
                            ("cost_signal_received", "Cost signal received"),
                            ("cost_ignored_non_primary", "Cost ignored (non-primary)"),
                            ("cost_ignored_no_link", "Cost ignored (no link)"),
                            ("cost_skipped_admin_override", "Cost skipped (admin override)"),
                            ("cost_skipped_resolution_failed", "Cost skipped (resolution failed)"),
                            ("manual_unlink", "Manual unlink from RealProduct"),
                            ("manual_merge", "Manual merge by EAN"),
                            ("physical_skipped", "Physical skipped (non-primary)"),
                            ("physical_overwrite", "Physical overwrite (opt-in)"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("field_path", models.CharField(db_index=True, max_length=128)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("applied_to_pim", models.BooleanField(default=False)),
                ("applied_to_pim_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="django_atlas.sourceproduct",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceProductLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("real_product_sku", models.CharField(db_index=True, max_length=128)),
                ("external_id", models.CharField(blank=True, default="", max_length=128)),
                ("priority", models.IntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "manual_override",
                    models.BooleanField(
                        default=False,
                        help_text="When True, auto-primary cron skips this link's RealProduct. Cleared by reset-to-auto.",
                    ),
                ),
                (
                    "preferred_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last is_primary=True flip. Used for cooldown check.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="django_atlas.source",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["idx"], name="django_atla_idx_0de926_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["is_active"], name="django_atla_is_acti_052f69_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["kind"], name="django_atla_kind_c1fe27_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["sku", "kind", "source", "-ts"], name="atlas_observation_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["kind", "-ts"], name="atlas_observation_kind_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcefeed",
            index=models.Index(fields=["source", "is_active"], name="django_atla_source__abb4d5_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourcefeed",
            constraint=models.UniqueConstraint(fields=("source", "idx"), name="uq_sourcefeed_source_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcemappingprofile",
            index=models.Index(fields=["source", "is_active"], name="django_atla_source__5be805_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourcemappingprofile",
            constraint=models.UniqueConstraint(fields=("source", "idx"), name="uq_sourcemappingprofile_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourcecategorymapping",
            constraint=models.UniqueConstraint(
                fields=("profile", "source_field", "source_value"), name="uq_sourcecategorymapping_profile_source_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceattributemapping",
            constraint=models.UniqueConstraint(
                fields=("profile", "source_field"), name="uq_sourceattributemapping_profile_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproduct",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="uq_sourceproduct_source_external"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(fields=["event_type", "severity"], name="django_atla_event_t_aeaeec_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(fields=["-created_at"], name="django_atla_created_a838db_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(fields=["acknowledged_at"], name="django_atla_acknowl_0ebffb_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceproductchangelog",
            index=models.Index(fields=["source_product", "-created_at"], name="atlas_changelog_sp_created_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceproductchangelog",
            index=models.Index(
                fields=["real_product_sku", "applied_to_pim", "-created_at"], name="atlas_changelog_sku_unseen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceproductchangelog",
            index=models.Index(fields=["source", "-created_at"], name="atlas_changelog_source_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceproductlink",
            index=models.Index(fields=["real_product_sku"], name="django_atla_real_pr_54280b_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceproductlink",
            index=models.Index(fields=["source"], name="django_atla_source__c66b80_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceproductlink",
            index=models.Index(fields=["manual_override"], name="django_atla_manual__5dfe3a_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourceproductlink",
            constraint=models.UniqueConstraint(
                fields=("real_product_sku", "source"), name="uq_sourceproductlink_sku_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproductlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("real_product_sku",),
                name="uq_sourceproductlink_one_primary_per_sku",
            ),
        ),
    ]
