# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.6 on 2026-08-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_atlas", "0001_squashed_0005_sourcesettings_feed_scheduling_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="auto_accept_min_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Reserved: lookup score above which a duplicate_in_pim proposal would be accepted automatically. NULL (default) = always review. Not used by v1.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="integrationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("feed_failed", "Feed failed"),
                    ("scraper_banned", "Scraper banned"),
                    ("scraper_dispatch_skipped", "Scraper dispatch skipped"),
                    ("image_failed", "Image failed"),
                    ("push_failed", "Push failed"),
                    ("push_succeeded", "Push succeeded"),
                    ("cost_updated", "Cost updated"),
                    ("mass_delisting", "Mass delisting"),
                    ("feed_no_run", "Feed no run"),
                    ("pim_feature_missing", "PIM feature missing"),
                    ("qms_not_installed_skipped", "QMS not installed (skipped)"),
                    ("qms_warehouse_not_configured", "QMS warehouse not configured"),
                    ("qms_write_failed", "QMS write failed"),
                    ("pushed_product_delisted", "Pushed product delisted"),
                    ("ean_collision_detected", "EAN collision detected"),
                    ("unknown_external_id_in_delta", "Unknown external_id in delta"),
                    ("physical_update_applied", "Physical update applied"),
                    ("force_repush_executed", "Force re-push executed"),
                    ("import_completed", "Import completed"),
                    ("source_deleted", "Source deleted"),
                    ("channel_removed_from_profile", "Channel removed from profile"),
                    ("attribute_value_missing", "Attribute value missing"),
                    ("pim_attribute_missing", "PIM attribute missing"),
                    ("pim_category_missing", "PIM category missing"),
                    ("pim_feature_set_missing", "PIM feature_set missing"),
                    ("pim_channel_missing", "PIM channel missing"),
                    ("image_download_started", "Image download started"),
                    ("image_download_completed", "Image download completed"),
                    ("multi_source_overlap", "Multi-source overlap"),
                    ("stock_updated", "Stock updated"),
                    ("qms_no_real_product", "QMS no real_product"),
                    ("cost_missing", "Cost missing"),
                    ("currency_missing", "Currency missing"),
                    ("scraper_results_validation_errors", "Scraper results validation errors"),
                    ("scraper_unknown_run_id", "Scraper unknown run_id"),
                    ("scraper_callback_signature_invalid", "Scraper callback signature invalid"),
                    ("source_credentials_viewed", "Source credentials viewed"),
                    ("source_credentials_updated", "Source credentials updated"),
                    ("language_fallback", "Language fallback"),
                    ("mapping_transform_failed", "Mapping transform failed"),
                    ("auto_linked_to_existing_realproduct", "Auto-linked to existing RealProduct"),
                    ("physical_tolerance_violation", "Physical tolerance violation"),
                    ("manual_unlink_from_realproduct", "Manual unlink from RealProduct"),
                    ("linked_via_lookup_proposal", "Linked via lookup proposal"),
                    ("linked_via_lookup_ui", "Linked via lookup UI"),
                    ("primary_source_switched", "Primary source switched"),
                    ("primary_source_emergency_switch", "Primary source emergency switch"),
                    ("primary_source_forced", "Primary source forced (manual override)"),
                    ("primary_switch_skipped_cooldown", "Primary switch skipped (cooldown)"),
                    ("primary_switch_skipped_hysteresis", "Primary switch skipped (hysteresis)"),
                    ("primary_switch_skipped_manual_override", "Primary switch skipped (manual override)"),
                    ("realproduct_manually_merged", "RealProduct manually merged"),
                    ("physical_update_skipped_non_primary", "Physical update skipped (non-primary)"),
                    ("physical_update_overwrite", "Physical update overwrite (opt-in non-primary)"),
                ],
                max_length=64,
            ),
        ),
    ]
